# VacationPy
----

#### Note
* Instructions have been included for each segment. You do not have to follow them exactly, but they are included to help you think through the steps.

In [1]:
# Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import requests
import gmaps
import os

# Import API key
from config import g_key

### Store Part I results into DataFrame
* Load the csv exported in Part I to a DataFrame

In [2]:
my_cities_to_load = 'C:\\Users\\me\\Desktop\\BBC\\COPY_but-ind-data-pt-06-2020-u-c\\Unit_06_Python_APIs\\Homework\\WeatherPy\\output_data\\my_cities\\my_cities.csv'
my_cities = pd.read_csv(my_cities_to_load)
my_cities.dropna(inplace = True) 
my_cities.head()

,City,Latitude,Longitude,Max Temperature,Humidity,Cloudiness,Wind Speed,Country,Date
0,busselton,-33.65,115.33,48.00,70.0,6.0,3.89,AU,1.595518e+09
2,lagunas,-5.23,-75.68,88.99,55.0,85.0,2.55,PE,1.595518e+09
3,plouzane,48.38,-4.62,71.60,49.0,26.0,8.05,FR,1.595519e+09
4,bluff,-46.60,168.33,39.00,83.0,83.0,3.00,NZ,1.595518e+09
5,hermanus,-34.42,19.23,66.00,73.0,0.0,2.59,ZA,1.595518e+09

### Humidity Heatmap
* Configure gmaps.
* Use the Lat and Lng as locations and Humidity as the weight.
* Add Heatmap layer to map.

In [3]:
gmaps.configure(api_key=g_key)

In [4]:
locations = my_cities[["Latitude", "Longitude"]]
weight = my_cities["Humidity"].astype(float)

fig = gmaps.figure()
heat_layer = gmaps.heatmap_layer(locations, weights=weight, 
                                  dissipating=False, max_intensity=10,
                                 point_radius=1)
fig.add_layer(heat_layer)
heat_layer.point_radius = 5
heat_layer.max_intensity = 100

fig

Figure(layout=FigureLayout(height='420px'))

### Create new DataFrame fitting weather criteria
* Narrow down the cities to fit weather conditions.
* Drop any rows will null values.

In [5]:
ideal_one = my_cities.loc[(my_cities["Max Temperature"] < 80)]
ideal_temp = ideal_one.loc[(ideal_one["Max Temperature"] > 70)]
ideal_wind = my_cities.loc[(my_cities["Wind Speed"] < 10)]
ideal_clouds =  my_cities.loc[(my_cities["Cloudiness"] < 1)]

In [6]:
ideal_wind_clouds = pd.merge(ideal_wind, ideal_clouds, on=["City", "City"])

In [7]:
ideal_conditions = pd.merge(ideal_temp, ideal_wind_clouds, on=["City", "City"])
ideal_conditions

,City,Latitude,Longitude,Max Temperature,Humidity,Cloudiness,Wind Speed,Country,Date,Latitude_x,...,Country_x,Date_x,Latitude_y,Longitude_y,Max Temperature_y,Humidity_y,Cloudiness_y,Wind Speed_y,Country_y,Date_y
0,limulunga,-15.10,23.14,70.99,23.0,0.0,4.14,ZM,1.595519e+09,-15.10,...,ZM,1.595519e+09,-15.10,23.14,70.99,23.0,0.0,4.14,ZM,1.595519e+09
1,east london,-33.02,27.91,75.20,33.0,0.0,6.93,ZA,1.595518e+09,-33.02,...,ZA,1.595518e+09,-33.02,27.91,75.20,33.0,0.0,6.93,ZA,1.595518e+09
2,cape town,-33.93,18.42,71.01,63.0,0.0,6.93,ZA,1.595518e+09,-33.93,...,ZA,1.595518e+09,-33.93,18.42,71.01,63.0,0.0,6.93,ZA,1.595518e+09
3,alvinopolis,-20.11,-43.05,76.75,47.0,0.0,5.68,BR,1.595519e+09,-20.11,...,BR,1.595519e+09,-20.11,-43.05,76.75,47.0,0.0,5.68,BR,1.595519e+09
4,frolovo,49.77,43.66,77.00,31.0,0.0,5.01,RU,1.595519e+09,49.77,...,RU,1.595519e+09,49.77,43.66,77.00,31.0,0.0,5.01,RU,1.595519e+09
5,ponta do sol,32.67,-17.10,73.00,65.0,0.0,0.60,PT,1.595518e+09,32.67,...,PT,1.595518e+09,32.67,-17.10,73.00,65.0,0.0,0.60,PT,1.595518e+09
6,kamenka,51.32,42.77,73.99,38.0,0.0,8.21,RU,1.595518e+09,51.32,...,RU,1.595518e+09,51.32,42.77,73.99,38.0,0.0,8.21,RU,1.595518e+09
7,mongu,-15.25,23.13,70.39,23.0,0.0,3.83,ZM,1.595519e+09,-15.25,...,ZM,1.595519e+09,-15.25,23.13,70.39,23.0,0.0,3.83,ZM,1.595519e+09
8,saldanha,-33.01,17.94,78.80,39.0,0.0,2.24,ZA,1.595518e+09,-33.01,...,ZA,1.595518e+09,-33.01,17.94,78.80,39.0,0.0,2.24,ZA,1.595518e+09
9,bayan,46.08,127.40,70.25,78.0,0.0,5.46,CN,1.595519e+09,46.08,...,CN,1.595519e+09,46.08,127.40,70.25,78.0,0.0,5.46,CN,1.595519e+09

In [8]:
ideal_conditions.drop(ideal_conditions.iloc[:, 8:25], inplace = True, axis = 1) 
ideal_conditions

,City,Latitude,Longitude,Max Temperature,Humidity,Cloudiness,Wind Speed,Country
0,limulunga,-15.10,23.14,70.99,23.0,0.0,4.14,ZM
1,east london,-33.02,27.91,75.20,33.0,0.0,6.93,ZA
2,cape town,-33.93,18.42,71.01,63.0,0.0,6.93,ZA
3,alvinopolis,-20.11,-43.05,76.75,47.0,0.0,5.68,BR
4,frolovo,49.77,43.66,77.00,31.0,0.0,5.01,RU
5,ponta do sol,32.67,-17.10,73.00,65.0,0.0,0.60,PT
6,kamenka,51.32,42.77,73.99,38.0,0.0,8.21,RU
7,mongu,-15.25,23.13,70.39,23.0,0.0,3.83,ZM
8,saldanha,-33.01,17.94,78.80,39.0,0.0,2.24,ZA
9,bayan,46.08,127.40,70.25,78.0,0.0,5.46,CN

In [9]:
ideal_conditions.drop(ideal_conditions.iloc[:, 4:4], inplace = True, axis = 1) 
ideal_conditions

,City,Latitude,Longitude,Max Temperature,Humidity,Cloudiness,Wind Speed,Country
0,limulunga,-15.10,23.14,70.99,23.0,0.0,4.14,ZM
1,east london,-33.02,27.91,75.20,33.0,0.0,6.93,ZA
2,cape town,-33.93,18.42,71.01,63.0,0.0,6.93,ZA
3,alvinopolis,-20.11,-43.05,76.75,47.0,0.0,5.68,BR
4,frolovo,49.77,43.66,77.00,31.0,0.0,5.01,RU
5,ponta do sol,32.67,-17.10,73.00,65.0,0.0,0.60,PT
6,kamenka,51.32,42.77,73.99,38.0,0.0,8.21,RU
7,mongu,-15.25,23.13,70.39,23.0,0.0,3.83,ZM
8,saldanha,-33.01,17.94,78.80,39.0,0.0,2.24,ZA
9,bayan,46.08,127.40,70.25,78.0,0.0,5.46,CN

### Hotel Map
* Store into variable named `hotel_df`.
* Add a "Hotel Name" column to the DataFrame.
* Set parameters to search for hotels with 5000 meters.
* Hit the Google Places API for each city's coordinates.
* Store the first Hotel result into the DataFrame.
* Plot markers on top of the heatmap.

In [10]:
ideal_conditions['Hotel Name'] = ""
ideal_conditions = ideal_conditions[["City","Country","Latitude","Longitude", "Hotel Name", "Max Temperature", "Cloudiness", "Wind Speed"]]
hotel_df = pd.DataFrame(ideal_conditions)
hotel_df

,City,Country,Latitude,Longitude,Hotel Name,Max Temperature,Cloudiness,Wind Speed
0,limulunga,ZM,-15.10,23.14,,70.99,0.0,4.14
1,east london,ZA,-33.02,27.91,,75.20,0.0,6.93
2,cape town,ZA,-33.93,18.42,,71.01,0.0,6.93
3,alvinopolis,BR,-20.11,-43.05,,76.75,0.0,5.68
4,frolovo,RU,49.77,43.66,,77.00,0.0,5.01
5,ponta do sol,PT,32.67,-17.10,,73.00,0.0,0.60
6,kamenka,RU,51.32,42.77,,73.99,0.0,8.21
7,mongu,ZM,-15.25,23.13,,70.39,0.0,3.83
8,saldanha,ZA,-33.01,17.94,,78.80,0.0,2.24
9,bayan,CN,46.08,127.40,,70.25,0.0,5.46

In [11]:
params = {
    "radius": 5000,
    "types": "lodging",
    "keyword": "hotel",
    "key": g_key
}


for index, row in hotel_df.iterrows():    
    lat = row["Latitude"]
    lng = row["Longitude"]   
    params["location"] = f"{lat},{lng}"    
    base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json" 
    hotel_address = requests.get(base_url, params=params)
    hotel_address = hotel_address.json()
    
    try:
        hotel_df.loc[index, "Hotel Name"] = hotel_address["results"][0]["name"]

    except (KeyError, IndexError):
        print("Missing field/result... skipping.")

Missing field/result... skipping.

In [12]:
hotel_df

,City,Country,Latitude,Longitude,Hotel Name,Max Temperature,Cloudiness,Wind Speed
0,limulunga,ZM,-15.10,23.14,Acamms Gardens,70.99,0.0,4.14
1,east london,ZA,-33.02,27.91,Premier Hotel Regent,75.20,0.0,6.93
2,cape town,ZA,-33.93,18.42,Atlanticview Cape Town Boutique Hotel,71.01,0.0,6.93
3,alvinopolis,BR,-20.11,-43.05,Hotel Nardy,76.75,0.0,5.68
4,frolovo,RU,49.77,43.66,Hotel Prizma,77.00,0.0,5.01
5,ponta do sol,PT,32.67,-17.10,Estalagem Da Ponta Do Sol,73.00,0.0,0.60
6,kamenka,RU,51.32,42.77,,73.99,0.0,8.21
7,mongu,ZM,-15.25,23.13,Acamms Gardens Lodge Mongu,70.39,0.0,3.83
8,saldanha,ZA,-33.01,17.94,Blue Bay Lodge,78.80,0.0,2.24
9,bayan,CN,46.08,127.40,Longfucheng Hotel,70.25,0.0,5.46

In [13]:
hotel_df = hotel_df.drop([6])
hotel_df

,City,Country,Latitude,Longitude,Hotel Name,Max Temperature,Cloudiness,Wind Speed
0,limulunga,ZM,-15.10,23.14,Acamms Gardens,70.99,0.0,4.14
1,east london,ZA,-33.02,27.91,Premier Hotel Regent,75.20,0.0,6.93
2,cape town,ZA,-33.93,18.42,Atlanticview Cape Town Boutique Hotel,71.01,0.0,6.93
3,alvinopolis,BR,-20.11,-43.05,Hotel Nardy,76.75,0.0,5.68
4,frolovo,RU,49.77,43.66,Hotel Prizma,77.00,0.0,5.01
5,ponta do sol,PT,32.67,-17.10,Estalagem Da Ponta Do Sol,73.00,0.0,0.60
7,mongu,ZM,-15.25,23.13,Acamms Gardens Lodge Mongu,70.39,0.0,3.83
8,saldanha,ZA,-33.01,17.94,Blue Bay Lodge,78.80,0.0,2.24
9,bayan,CN,46.08,127.40,Longfucheng Hotel,70.25,0.0,5.46

In [14]:
# NOTE: Do not change any of the code in this cell

# Using the template add the hotel marks to the heatmap
info_box_template = """
<dl>
<dt>Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
</dl>
"""
# Store the DataFrame Row
# NOTE: be sure to update with your DataFrame name
# hotel_df = [info_box_template.format(**row) for index, row in hotel_df.iterrows()]

# #save to a different dataframe not hotel_df
# locations = hotel_df[["Latitude", "Longitude"]]
# locations

In [15]:
hotel_locations = hotel_df[["Latitude", "Longitude"]]

In [16]:

markers = gmaps.marker_layer(hotel_locations)

fig.add_layer(markers)


fig

Figure(layout=FigureLayout(height='420px'))